// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PIIServiceClient is the client API for PIIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PIIServiceClient interface {
	GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataReply, error)
}

type pIIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPIIServiceClient(cc grpc.ClientConnInterface) PIIServiceClient {
	return &pIIServiceClient{cc}
}

func (c *pIIServiceClient) GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataReply, error) {
	out := new(GetDataReply)
	err := c.cc.Invoke(ctx, "/pii.PIIService/GetData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PIIServiceServer is the server API for PIIService service.
// All implementations must embed UnimplementedPIIServiceServer
// for forward compatibility
type PIIServiceServer interface {
	GetData(context.Context, *GetDataRequest) (*GetDataReply, error)
	mustEmbedUnimplementedPIIServiceServer()
}

// UnimplementedPIIServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPIIServiceServer struct {
}

func (UnimplementedPIIServiceServer) GetData(context.Context, *GetDataRequest) (*GetDataReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetData not implemented")
}
func (UnimplementedPIIServiceServer) mustEmbedUnimplementedPIIServiceServer() {}

// UnsafePIIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PIIServiceServer will
// result in compilation errors.
type UnsafePIIServiceServer interface {
	mustEmbedUnimplementedPIIServiceServer()
}

func RegisterPIIServiceServer(s grpc.ServiceRegistrar, srv PIIServiceServer) {
	s.RegisterService(&PIIService_ServiceDesc, srv)
}

func _PIIService_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PIIServiceServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pii.PIIService/GetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PIIServiceServer).GetData(ctx, req.(*GetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PIIService_ServiceDesc is the grpc.ServiceDesc for PIIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PIIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pii.PIIService",
	HandlerType: (*PIIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetData",
			Handler:    _PIIService_GetData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pii/pii.proto",
}
