AWSTemplateFormatVersion: "2010-09-09"
Description: ECR repositories


Parameters:
  ProjectName:
    Type: String


Resources:
  IdentityServiceRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${ProjectName}-svc-identity

  PIIServiceRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${ProjectName}-svc-pii

  ProfileServiceRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${ProjectName}-svc-profile

  ClientServiceRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${ProjectName}-svc-client


Outputs:
  IdentityServiceRepository:
    Value: !Ref IdentityServiceRepository
    Export:
      Name: !Sub ${ProjectName}:IdentityServiceRepository
  PIIServiceRepository:
    Value: !Ref PIIServiceRepository
    Export:
      Name: !Sub ${ProjectName}:PIIServiceRepository
  ProfileServiceRepository:
    Value: !Ref ProfileServiceRepository
    Export:
      Name: !Sub ${ProjectName}:ProfileServiceRepository
  ClientServiceRepository:
    Value: !Ref ClientServiceRepository
    Export:
      Name: !Sub ${ProjectName}:ClientServiceRepository
