AWSTemplateFormatVersion: "2010-09-09"
Description: AppMesh defintitions


Parameters:
  ProjectName:
    Type: String
    Description: Project name to link stacks


Resources:
  Mesh:
    Type: AWS::AppMesh::Mesh
    Properties:
      MeshName: !Sub ${ProjectName}-mesh

  ClientServiceNode:
    Type: AWS::AppMesh::VirtualNode
    Properties:
      MeshName: !GetAtt Mesh.MeshName
      VirtualNodeName: svc-client
      Spec:
        Backends:
          - VirtualService:
              VirtualServiceName: !GetAtt VirtualIdentityService.VirtualServiceName
        Listeners:
          - PortMapping:
              Port: 8080
              Protocol: http
        ServiceDiscovery:
          AWSCloudMap:
            # FIXME This is defined in ecs.yml
            NamespaceName: !Sub ${ProjectName}.local
            ServiceName: svc-client

  # This node acts as a logical pointer to the ECS identity service.
  # The ServiceDiscovery spec references the Registry created in services/identity.yml.
  IdentityServiceNode:
    Type: AWS::AppMesh::VirtualNode
    Properties:
      MeshName: !GetAtt Mesh.MeshName
      VirtualNodeName: svc-identity
      Spec:
        Listeners:
        - PortMapping:
            Port: 8080
            Protocol: grpc
          HealthCheck:
            HealthyThreshold: 2
            IntervalMillis: 5000
            TimeoutMillis: 2000
            UnhealthyThreshold: 3
            Port: 8080
            Protocol: grpc
        ServiceDiscovery:
          AWSCloudMap:
            NamespaceName: !Sub ${ProjectName}.local
            ServiceName: svc-identity

  VirtualIdentityRouter:
    Type: AWS::AppMesh::VirtualRouter
    Properties:
      MeshName: !GetAtt Mesh.MeshName
      VirtualRouterName: virtual-identity-router
      Spec:
        Listeners:
        - PortMapping:
            Port: 8080
            Protocol: grpc

  VirtualIdentityService:
    Type: AWS::AppMesh::VirtualService
    Properties:
      MeshName: !GetAtt Mesh.MeshName
      VirtualServiceName: !Sub svc-identity.${ProjectName}.local
      Spec:
        Provider:
          VirtualRouter:
            VirtualRouterName: !GetAtt VirtualIdentityRouter.VirtualRouterName

  IdentityServiceRoute:
    Type: AWS::AppMesh::Route
    Properties:
      MeshName: !GetAtt Mesh.MeshName
      VirtualRouterName: !GetAtt VirtualIdentityRouter.VirtualRouterName
      RouteName: svc-identity-route
      Spec:
        GrpcRoute:
          Action:
            WeightedTargets:
            - VirtualNode: !GetAtt IdentityServiceNode.VirtualNodeName
              Weight: 100
          Match:
            ServiceName: identity.IdentityService
            # MethodName: IssueToken # Can restrict to specific methods
