AWSTemplateFormatVersion: "2010-09-09"
Description: AppMesh defintitions


Parameters:
  ProjectName:
    Type: String
    Description: Project name to link stacks


Resources:
  Mesh:
    Type: AWS::AppMesh::Mesh
    Properties:
      MeshName: !Sub ${ProjectName}-mesh

  ClientServiceNode:
    Type: AWS::AppMesh::VirtualNode
    Properties:
      MeshName: !GetAtt Mesh.MeshName
      VirtualNodeName: svc-client
      Spec:
        Backends:
          - VirtualService:
              VirtualServiceName: !Sub svc-identity.${ProjectName}.local
        Listeners:
          - PortMapping:
              Port: 8080
              Protocol: http
        ServiceDiscovery:
          AWSCloudMap:
            # FIXME This is defined in ecs.yml
            NamespaceName: !Sub ${ProjectName}.local
            ServiceName: svc-client

  IdentityServiceNode:
    Type: AWS::AppMesh::VirtualNode
    Properties:
      MeshName: !GetAtt Mesh.MeshName
      VirtualNodeName: svc-identity
      Spec:
        Listeners:
        - PortMapping:
            Port: 8080
            Protocol: grpc
          HealthCheck:
            HealthyThreshold: 2
            IntervalMillis: 5000
            TimeoutMillis: 2000
            UnhealthyThreshold: 3
            Port: 8080
            Protocol: grpc
        ServiceDiscovery:
          AWSCloudMap:
            NamespaceName: !Sub ${ProjectName}.local
            ServiceName: svc-identity

  VirtualRouter:
    Type: AWS::AppMesh::VirtualRouter
    Properties:
      MeshName: !GetAtt Mesh.MeshName
      VirtualRouterName: virtual-router
      Spec:
        Listeners:
        - PortMapping:
            Port: 8080
            Protocol: grpc

  VirtualService:
    DependsOn:
     - VirtualRouter
    Type: AWS::AppMesh::VirtualService
    Properties:
      MeshName: !GetAtt Mesh.MeshName
      VirtualServiceName: !Sub svc-identity.${ProjectName}.local
      Spec:
        Provider:
          VirtualRouter:
            VirtualRouterName: virtual-router

  Route:
    DependsOn: [ VirtualRouter, IdentityServiceNode ]
    Type: AWS::AppMesh::Route
    Properties:
      MeshName: !GetAtt Mesh.MeshName
      VirtualRouterName: virtual-router
      RouteName: route
      Spec:
        GrpcRoute:
          Action:
            WeightedTargets:
            - VirtualNode: svc-identity
              Weight: 100
          Match:
            ServiceName: identity.IdentityService
            # MethodName: IssueToken # Can restrict to specific methods
